#include <cctype>
#include <iostream>
#include <string>
#include <vector>

std::string transformChar( const char in_char )
{   /* take input character and transform it so that it:
    1. alphabetical characters are converted into upper case
    2. digits are replaced with their english equivalent words
    3. all other characters are disregarded

    char in_char: the character to transform

    return: the string generated by the transformed character
    */

    //initialise input text
    std::string inputText;
    // Uppercase alphabetic characters
    if (std::isalpha(in_char)) {
        inputText += std::toupper(in_char);
        return inputText; // returns this now since we don't continue when not in a while loop
        // i.e we don't have any other characters yet since we haven't looped over to them,
        // simply return the input text here.
    }

    // Transliterate digits to English words
    switch (in_char) {
        case '0':
            inputText += "ZERO";
            break;
        case '1':
            inputText += "ONE";
            break;
        case '2':
            inputText += "TWO";
            break;
        case '3':
            inputText += "THREE";
            break;
        case '4':
            inputText += "FOUR";
            break;
        case '5':
            inputText += "FIVE";
            break;
        case '6':
            inputText += "SIX";
            break;
        case '7':
            inputText += "SEVEN";
            break;
        case '8':
            inputText += "EIGHT";
            break;
        case '9':
            inputText += "NINE";
            break;
    }

    // if character non alphabetic/numeric we DON'T add it (i.e. we remove it)

    return inputText;
}